export const GET_PIZZAS_REQUEST = 'GET_PIZZAS_REQUEST'
export const GET_PIZZAS_SUCCESS = 'GET_PIZZAS_SUCCESS'
export const GET_PIZZAS_FAIL = 'GET_PIZZAS_FAIL'

export const GET_SINGLE_PIZZA_REQUEST = 'GET_SINGLE_PIZZA_REQUEST'
export const GET_SINGLE_PIZZA_SUCCESS = 'GET_SINGLE_PIZZA_SUCCESS'
export const GET_SINGLE_PIZZA_FAIL = 'GET_SINGLE_PIZZA_FAIL'